//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseDesign.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductInfo
    {
        public ProductInfo()
        {
            this.IsDelete = false;
            this.Provider = new HashSet<Provider>();
            this.SellInfo = new HashSet<SellInfo>();
            this.ProductEvaluate = new HashSet<ProductEvaluate>();
        }
    
        public System.Guid PdId { get; set; }
        public string PdName { get; set; }
        public double PdPrice { get; set; }
        public string ProductDescribe { get; set; }
        public string Remark { get; set; }
        public bool IsDelete { get; set; }
        public System.DateTime SubTime { get; set; }
        public int PdNum { get; set; }
    
        public virtual ICollection<Provider> Provider { get; set; }
        public virtual ICollection<SellInfo> SellInfo { get; set; }
        public virtual ICollection<ProductEvaluate> ProductEvaluate { get; set; }
    }
}
