//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseDesign.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public UserInfo()
        {
            this.IsDelete = false;
            this.ProductEvaluate = new HashSet<ProductEvaluate>();
            this.OrderInfo = new HashSet<OrderInfo>();
            this.BuyInfo = new HashSet<BuyInfo>();
        }
    
        public System.Guid UserId { get; set; }
        public string Name { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<bool> Sex { get; set; }
        public string Phone { get; set; }
        public bool IsDelete { get; set; }
        public string Remark { get; set; }
        public System.DateTime SubTime { get; set; }
        public System.DateTime RegisteTime { get; set; }
        public string Account { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<ProductEvaluate> ProductEvaluate { get; set; }
        public virtual ICollection<OrderInfo> OrderInfo { get; set; }
        public virtual ICollection<BuyInfo> BuyInfo { get; set; }
    }
}
