//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseDesign.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataBaseDesignModelContainer : DbContext
    {
        public DataBaseDesignModelContainer()
            : base("name=DataBaseDesignModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UserInfo> UserInfo { get; set; }
        public virtual DbSet<ProductInfo> ProductInfo { get; set; }
        public virtual DbSet<Provider> Provider { get; set; }
        public virtual DbSet<ProductEvaluate> ProductEvaluate { get; set; }
        public virtual DbSet<BuyInfo> BuyInfo { get; set; }
        public virtual DbSet<SellInfo> SellInfo { get; set; }
        public virtual DbSet<OrderInfo> OrderInfo { get; set; }
        public virtual DbSet<ApiAuthorityVerification> ApiAuthorityVerification { get; set; }
    }
}
